### ISSUE TITLE
Exception on build.py

### ISSUE THREAD

**Issue by avalon60** [dishb/hive#3]
OK @dishb,  with the fix to issue #1, I have gotten a little further, but now I get this:

```
python3 ./utility/build.py
Traceback (most recent call last):
  File "/usr/lib/python3.10/shutil.py", line 815, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/home/clive/PycharmProjects/hive/./dist/hive.app' -> '/Applications/'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/clive/PycharmProjects/hive/./utility/build.py", line 66, in <module>
    move(f"{REPO_LOC}/dist/hive.app", "/Applications/")
  File "/usr/lib/python3.10/shutil.py", line 835, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/clive/PycharmProjects/hive/./dist/hive.app'
```
Maybe the Applications is a Mac specific folder?

**Comment by dishb** [comment]
`/Applications/` is a folder on macOS. Located in the root of the file system. It is probably specific to macOS only (and not on Linux or Windows). 

It also looks like the program isn't recognizing the "." as a relative path. This may also be specific to macOS. 

- "." represents "in the same parent directory". 
- ".." represents "in one directory above".

I need to add proper paths for Windows and Linux. Similar to issue #3.

**Comment by avalon60** [comment]
Those dot notations (. and ..) are used by all UNIX (and therefore Linux) operating systems.

**Comment by dishb** [comment]
Okay, thank you- that's important. I'll try to find out the issue. Unfortunately, I don't have a Windows or Linux machine for testing. 

The issue you are experiencing doesn't show up on my end (ah the famous words "it works on my machine").

I'll try to fix it as soon as possible. Thank you.

**Comment by avalon60** [comment]
The dot in the middle of the path is odd and looks wrong.

**Comment by dishb** [comment]
I'm assuming that's the problem. I hope migrating my paths to `pathlib.Path()` will solve most of these issues.

**Comment by avalon60** [comment]
Well on the face of it, it just looks like a path that has been constructed incorrectly. As though you have concatenated a relative pathname to a base path. 

The way I avoid much of these complications is by converting to a full path. You can that with with Pathlib. It has an absolute() method:

E.g.

```
hive_dir = Path('./hive')
abs_hive = hive_dir.absolute()
```
Assuming the hive directory was in /home/clive, then abs_hive would be /home/clive/hive

**Comment by avalon60** [comment]
I hate typing on a tablet!  :o)

**Comment by dishb** [comment]
I'm looking through the [build script](https://github.com/dishb/hive/blob/main/utility/build.py) and I haven't used any relative paths or string concatenation to join paths. I've used formatted "f-strings" to get the absolute paths. But again, no dot notation.

Let me try refactoring the whole codebase to use `pathlib.Path()`. We can move forward from there.

**Comment by avalon60** [comment]
What is it you are doing with the Application directory. Are you trying to soft link the app, so that it becomes available through the Mac interface somehow?

**Comment by dishb** [comment]
To make the build script "ultra-convenient" (ironic due to the number of bugs), I made the build script...
- delete all extra files and directories created by Pyinstaller (while building)
- move the created `hive.app` file to the macOS `/Applications/` folder

**Comment by dishb** [comment]
Hi @avalon60,

I've just made [a commit](https://github.com/dishb/hive/commit/69c9280ea3889e133a9fac579b2eff2429b51f20) that updates the build script (`./utility/build.py`) to use `pathlib.Path()` for the paths. I believe the build script should work now.

Could you please test the script for me? Thank you.

I think it is important to note that **the rest of the codebase is not using `pathlib.Path()` yet.** You may still encounter errors when trying to open or use the actual application. This commit **only fixes issues in build script.**

**Comment by avalon60** [comment]
> Hi @avalon60,
> 
> I've just made [a commit](https://github.com/dishb/hive/commit/69c9280ea3889e133a9fac579b2eff2429b51f20) that updates the build script (`./utility/build.py`) to use `pathlib.Path()` for the paths. I believe the build script should work now.
> 
> Could you please test the script for me? Thank you.
> 
> I think it is important to note that **the rest of the codebase is not using `pathlib.Path()` yet.** You may still encounter errors when trying to open or use the actual application. This commit **only fixes issues in build script.**
> 
> If the build script works, please mark as resolved. As for using `pathlib.Path()` in the rest of the codebase, we can proceed with that in #2.
Hi @dishb. I did a fresh clone of the repo. Nice to see you have quickly transitioned to venv!

Everything went well, with the new instructions, until I tried the build:

```
python3 ./utility/build.py
Traceback (most recent call last):
  File "/home/clive/PycharmProjects/testproj/hive/./utility/build.py", line 39, in <module>
    output = run([PIP_CMD, "show", "customtkinter"], check = True, capture_output = True).stdout
NameError: name 'PIP_CMD' is not defined

```

**Comment by dishb** [comment]
Oh wow that's great! I'll change the code to add Linux support. I wasn't sure if Linux used `pip3` like macOS. Thank you for your work in identifying and fixing the issue(s)!

**Comment by dishb** [comment]
@avalon60 - I've fixed the error you mentioned here:
```
python3 ./utility/build.py
Traceback (most recent call last):
  File "/home/clive/PycharmProjects/testproj/hive/./utility/build.py", line 39, in <module>
    output = run([PIP_CMD, "show", "customtkinter"], check = True, capture_output = True).stdout
NameError: name 'PIP_CMD' is not defined
```
Linux is now supported with [this commit](https://github.com/dishb/hive/commit/a081fa137071fa8d441e49882c1badc10c284022).

**Comment by dishb** [comment]
@avalon60 - Just wanted to let you know, I'm adding the image you provided to the showcase images. Thank you!
